### ISSUE TITLE
Jasmine 2.0?

### ISSUE THREAD

**Issue by GetContented** [spra85/jasmine-ember-testing#1]
Hiya,

Can I help out with Jasmine 2 support? What needs to be done?

I've just been dipping my toe into converting all my qunit tests to jasmine because I really need multiple describe blocks, and I've gotten as far as Ember not actually rendering my content on the page. That's when I remembered oh yeah I need to address all the async stuff.. That's how I ended up here :)

**Comment by spra85** [comment]
With the changes on Jasmine 2.0 async support, it's a different animal, which I think you could largely address with how you structure your tests.  For instance: 

```
describe("posts", function() {
  beforeEach(function(done) {
    visit("/posts");
    click("foo");
    click("bar")
    andThen(function() {
      done();
    });
  });

  it("should", function() {
    expect(find("baz")).toExist();
  });
});
```

I've bounced back and forth on how to implement the actual asyncStart and asyncEnd functions required by the Ember test adapter, but unless I'm missing something glaring it seems for simple tests just having empty functions and structuring your integration tests like above would handle most use cases.  I know Ted Zeenny has implemented an adapter for mocha (https://github.com/teddyzeenny/ember-mocha-adapter) and I believe Jasmine's async support is based on mocha's so there may be some parallels we can use.

**Comment by GetContented** [comment]
Oh okay that sounds great. Actually it's not an integration test I'm having an issue with, it's testing a component in isolation. I'm trying to append a component to a view (which works fine in qunit), but there's no div called ember-testing because there's no body after Ember.reset() (it seems).

Maybe the issue I'm having isn't what I thought it was: (Ember.reset() seems to be blanking out the body of the html document). I have the following in my spec_helper file, but Ember.reset() calls seem to be removing the body element:

```
document.write('<div id="ember-testing-container"><div id="ember-testing"><script type="text/x-handlebars"><div id="container">{{partial "menu"}}{{outlet}}</div></script></div></div>')
document.write('<style>#ember-testing-container { position: absolute; background: white; bottom: 0; right: 0; width: 640px; height: 384px; overflow: auto; z-index: 9999; border: 1px solid #ccc; } #ember-testing { zoom: 50%; } #qunit-fixture {display: "block"; visibility: visible;}</style>')

Simplecms.rootElement = '#ember-testing'
Simplecms.ApplicationAdapter = DS.FixtureAdapter.extend()
Simplecms.setupForTesting()
Simplecms.injectTestHelpers()
```

I was assuming this was a problem with the async stuff, but assumptions are bad to make, right? :)

Hm...

**Comment by GetContented** [comment]
Sorry I should amend that - it _is_ an integration test in as much as I'm testing the component and its behaviour rendered in the browser... but it's not actually testing the particular component in-situ... to that end, I append the component to the test and try to test it... 

but the major issue seems to be that the document doesn't have the correct context... Do you have any similar experience with using jasmine to insert HTML and Ember objects, etc and test them, but not actually visiting any routes?

**Comment by spra85** [comment]
I do, but always varies on the situation and depending on the component you have to tinker with the ember container occasionally.  For unit testing some components, I use jasmine fixtures though you can also instantiate a view pretty easily with an ember object and the handlebars template

**Comment by GetContented** [comment]
The ember-mocha-adapter you linked is a bit tricky for first time ember-testing-adapter readers :-) Time to check out the ember testing code :( :)

**Comment by GetContented** [comment]
Not really having trouble instantiating a view - got that working just fine in qunit. It's not great fun, but it's understandable and working. :) Trouble seems to be that jasmine isn't waiting for the view to render before running its tests (as one would expect just using Jasmine without hooking into Ember-Testing's start and stop methods). Will investigate more. :)

**Comment by GetContented** [comment]
Hi man thanks for all your help. I've put your adapter into my app, and it seems to be running just fine with Jasmine 2. Still a bit confused, though, because after reading the mocha adapter more and reading up in the source of ember-testing a little more, (which was surprisingly clear), it seemed one would need to run done() in the async stuff, but so far hasn't seen it necessary at all.

**Comment by spra85** [comment]
@JulianLeviston meant to respond to you but I reached out to Stefan Penner on the Ember core team who was really helpful -- he mentioned with Ember 1.6+, the test adapter abstraction won't be as important because of the built in promises support.  Be interesting to keep an eye on the ember-testing package in the next handful of months -- i think it'd be great if there wasn't as much of a dependency on that adapter

**Comment by GetContented** [comment]
Yeah Stefan's a legend. :) Cool Cool... well it's all good for now.

**Comment by JackCA** [comment]
Just stumbled upon this as well. Not having as much luck as @JulianLeviston with using this with 2.0, but it works great with 1.3. Tracking this issue for future reference. Will personally be looking at that mocha implementation to see if there's anything we can use moving forward. Thanks @spra85!

**Comment by GetContented** [comment]
@JackCA  I actually didn't have to do too much to get it working... I think :) I did have to use this adapter, but yeah... You're not having as much.... what exactly? luck? :) (thinking there might be a word missing there).

**Comment by JackCA** [comment]
@JulianLeviston whoops. Sorry about that. Yes, "luck." Are you using integration tests?

**Comment by GetContented** [comment]
Yeah I'm doing integration tests. Ugly, Ugly integration tests. Their ugliness has nothing to do with Jasmine, though, has more to do with my lack of ability to separate out my data factories (and the fact that I've built quite a complicated system without writing enough tests from the beginning - shifting into TDD after the project was about 6-8 months old kinda sucked).

[ edit ] I'd recommend liberal use of andThen() and Ember.run() calls to ensure correct sequencing. Things can get a bit hairy if you don't fully understand what's going on there.

**Comment by vire** [comment]
Hi guys, did somebody of you succeeded meanwhile at integrating jasmine 2.0 into an ember/ember-cli project? Mainly the part with supporting the ember- async helpers. I've looked at the mocha adapter- but without success.

Thx for any ideas.

**Comment by JackCA** [comment]
@vire No, actually. I use this adapter with good ol' Jasmine 1.3 and it works great -- however, I'm on the lookout for a solution that works smoothly with 2.0.

**Comment by vire** [comment]
Yeah I've read about that option (to use jasmine 1.3) above, but I'm not gonna write dozen of tests, they would need to be refactored once I switch to Jasmine2. I've took a look at the original ember [qunit-adapter](https://github.com/emberjs/ember.js/blob/071b4bb6aad44100dc74ef8e1c79562e57038e7d/packages/ember-testing/lib/adapters/qunit.js) it doesn't very make sense to me how it works, and how this should work in jasmine2... Also the [test](https://github.com/emberjs/ember.js/blob/7cc694ef8c32f0dba429962f29cdbd9203d223dd/packages/ember-testing/tests/adapters/qunit_test.js) for the adapter doesn't make sense at all to me.

has somebody analyzed more deepley, how the asynch adater methods are used during the tests? Unsless I don't use the async helpers, do I need the jasmine-adapter? Unit tests on the App object, controllers are passing for now (but I'm creating the the App instances in the beforeEach methods.

@JackCA could you post a link to simple tests or gists? Thx very much!

**Comment by GetContented** [comment]
I _thought_ I was using Jasmine 2 because, well, I thought I'd configured Teaspoon to work with jasmine 2.... so it seems I'm using jasmine 2, but I really have no idea, and my tests seem to work with both if at all.

**Comment by ryrych** [comment]
Hi, any update for 2.0 :)

**Comment by spra85** [comment]
hey @ryrych, there's people that have had success getting it to work just fine with Jasmine 2.0.  With the Ember integration test helpers built-in promises support the test adapter abstraction should hopefully be fading away altogether, meaning you should be able to use --insert .js test framework here--.  The only thing you might want to look into is if you're doing integration tests, to use the jasmine async support potentially in your `beforeEach`..e.g. something like: 

```
beforeEach(function(done) {
  visit('comments/1');
  fillIn(#title, 'My Title');
  click('Update');
  andThen(function() {
    done();
  });
});

it('updates the title', function() {
  expect(find('#title').text()).toEqual('My Title');
});
```

I will say that a few people in our office have switched to using Mocha and prefer that, and a few others have started looking into https://github.com/square/qunit-bdd as another BDD syntax alternative to jasmine.

**Comment by vire** [comment]
@ryrych @spra85 I've switched a week ago to Mocha. First, it was quite better than Jasmine 2.0 from the aspect of ember/ember-cli support - mainly thanks to tedd zeeny's asynch adapter. I could write awesome tests for particular Ember object.
But then i needed to utilize the container and run loop and have the same support that ember-qunit offers - using [ember-qunit#mocha](https://github.com/WMeldon/ember-qunit/tree/mocha). 

If somebody competent, experienced with superior ember core knowledge, could or would write a solid Jasmine adapter and test container initializer, i would lovely use jasmine/mocha instead of qunit.

**Comment by ryrych** [comment]
@spra85 Maybe it's the problem with our setup. I'll try to look at it closely.
